# Generated by Django 4.2.7 on 2023-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_contact_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='nazbeen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='nazbeen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='nazbeen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='nazbeen'),
            preserve_default=False,
        ),
    ]
